version: '3.4'

services:
  redisdb:
    image: redis

  mongodb:
    image: mongo

  mssqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  rabbitmq:
    image: rabbitmq:3-management


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Filmos_basket/Basket.API/Dockerfile

  rating.api:
    image: ${DOCKER_REGISTRY-}rating.api
    build:
      context: .
      dockerfile: src/Services/Filmos_rating/WebUI/Dockerfile

  favorite.api:
    image: ${DOCKER_REGISTRY-}favorite.api
    build:
      context: .
      dockerfile: src/Services/Filmos_favorites/EFCoreCodeFirstSampleWEBAPI/Dockerfile

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: src/ApiGateways/OcelotApiGw/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3

volumes:
  elasticsearch-data: