version: '3.4'

services:
  redisdb:
    container_name: redisDB_compose
    restart: always    
    ports:
        - "6379:6379"

  mongodb:
    container_name: mongodb_compose
    restart: always
    ports:
        - "27017:27017"

  mssqldb:
    container_name: mssqlDB_compose
    restart: always
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"

  rabbitmq:
    container_name: RabbitMQ_compose
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"


  basket.api:
    container_name: Basket.API_compose
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "CacheSettings:ConnectionString=redisdb:6379"
    depends_on:
      - redisdb
    ports:
      - "8001:80"

  rating.api:
    container_name: Rating.API_compose
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "FilmosDatabase:ConnectionString=mongodb://mongodb:27017"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "8002:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  favorite.api:
    container_name: Favorite.API_compose
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - mssqldb
      - rabbitmq
    ports:
      - "8000:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ocelotapigw:
    container_name: OcelotAPIGW_compose
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - basket.api
      - rating.api
    ports:
      - "8010:80"

  elasticsearch:
    container_name: elasticsearch_compose
    environment:
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana_compose
    environment:        
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601"  